# Generated by Django 5.2.1 on 2025-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(),
        ),
    ]
